#!/usr/bin/env bash
# This script displays the DNS record type and IP address of specified subdomains

get_subdomain_info() {
    local domain=$1
    local subdomain=$2
    
    # shellcheck disable=SC2086
    local destination=$(host ${subdomain}.${domain} | awk '/has address/ {print $4}')
    
    if [ -n "$destination" ]; then
        echo "The subdomain ${subdomain} is a A record and points to ${destination}"
    fi
}

domain=$1
subdomain=$2

if [ -z "$subdomain" ]; then
    for sd in www lb-01 web-01 web-02; do
        get_subdomain_info "$domain" "$sd"
    done
else
    get_subdomain_info "$domain" "$subdomain"
fi
